### ISSUE TITLE
Hitch Warnings by esx_status

### ISSUE THREAD

**Issue by AI-Wall3** [esx-framework/esx_status#15]
![esx_status](https://github.com/user-attachments/assets/1063b12e-e7de-4541-9a6c-eec9f6608938)
I dont know why it make so high ticks on server with 16 players

**Comment by Mycroft-Studios** [comment]
What hosting do you use for your server?

**Comment by Mycroft-Studios** [comment]
Which provider?

**Comment by Mycroft-Studios** [comment]
so, a VPS or dedicated server, right?

**Comment by Kenshiin13** [comment]
@AI-Wall3 Can you please try the newest version of esx_status
