### ISSUE TITLE
Issue when someone die by hunger or thirst

### ISSUE THREAD

**Issue by LordDrack1** [esx-framework/esx_status#63]
i have this issue , only happen when someone die by hunger or thirst , when the player respawn with 50% of hunger and thirst the health keep going down inclusive when the player eat and drink for reach the 100%

**Comment by davuongthanh** [comment]
metoo

**Comment by LordDrack1** [comment]
> Not something I can reproduce - are you using the latest versions of both esx_status and esx_basicneeds?

yes , i use the lastest version but i think the problem was es_extended cuz i made another server but now with extendedmode and work, i dont know why , but now work fine
