### ISSUE TITLE
[Feature Request] - Armor and Health saving

### ISSUE THREAD

**Issue by TheFantomas** [esx-framework/esx_status#7]
It would be good to also save Armor and Health in the database.

**Comment by Gellipapa** [comment]
Metadata system can handle.

**Comment by Gellipapa** [comment]
We need to do it.

**Comment by MoskalykA** [comment]
@Gellipapa I'm interested in doing this

**Comment by Gellipapa** [comment]
Close because we implemented this [#1193](https://github.com/esx-framework/esx_core/pull/1193) issue.
